---
- name: Run RansomwarePoC
  hosts: rpis
  remote_user: root
  tasks:
    #     - name: Test access and FS
    #   command: "touch /tmp/ansible_was_here"
    #
     - name: Delete ransomware files (old ones)
       file:
         state: absent
         path: /home/pi/ransomwarefiles

     - name: Create encryption directory
       ansible.builtin.file:
         path: /home/pi/ransomwarefiles
         state: directory


     - name: Copy sample PDFs to encrypt
       ansible.builtin.unarchive:
         src: assets/sample_files_to_encrypt.zip
         dest: /home/pi/ransomwarefiles

     - name: Run python script
       shell: |
         python3 /opt/ransomwarepoc/main.py -p "/home/pi/ransomwarefiles" -e
       args:
         executable: /bin/bash

