---
- name: Install C&C MTD
  hosts: rpis
  remote_user: root
  tasks:
     - name: Test access and FS
       command: "touch /tmp/ansible_was_here"

     - name: Install arp-scan
       apt:
         name: arp-scan
         state: present

     - name: Copy CnC MTD from framework
       ansible.builtin.copy: src={{ item.src }} dest={{ item.dest }} remote_src=yes
       with_items:
         - { src: '/opt/MTDFramework/Framework/CnC', dest: '/opt/MTDFramework/CnC'}
